org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=birdsnests
mod_name=Birds Nests
mod_license=GNU LESSER GENERAL PUBLIC LICENSE
mod_version=1.20.1-2.1.5
mod_group_id=panda.birds_nests
mod_authors=Cleverpanda714 for all the versions below 1.14.4 and RedRoseWarrior for all versions past 1.14.4
mod_description=pseudo-random reward events from chopping trees

